build:
  builder: heroku/php
  plugins:
    - name: heroku-community/php
      settings:
        # Esto instala y activa el módulo PDO MySQL en el contenedor PHP.
        php_extensions:
          - pdo-mysql
